### ISSUE TITLE
Error when setting maxHeight on a datatable

### ISSUE THREAD

**Issue by glenbray** [tabulator-tables/tabulator#4419]
**Describe the bug**

When setting maxHeight on Tabulator the page crashes. The jsfiddle won't crash but it will output the error related in dev tools. The task manager in Chrome does show it running at 100% CPU also.  

Error from console:

```
Uncaught (in promise) RangeError: Maximum call stack size exceeded 
at VirtualDomVertical._virtualRenderFill (VirtualDomVertical.js:225:20) 
at VirtualDomVertical.rerenderRows (VirtualDomVertical.js:101:9) 
at RowManager.reRenderInPosition (RowManager.js:854:18) 
at RowManager.redraw (RowManager.js:1116:9) 
at RowManager.adjustTableSize (RowManager.js:1069:11) 
at VirtualDomVertical._virtualRenderFill (VirtualDomVertical.js:346:37) 
at VirtualDomVertical.rerenderRows (VirtualDomVertical.js:101:9) 
at RowManager.reRenderInPosition (RowManager.js:854:18) 
at RowManager.redraw (RowManager.js:1116:9) 
at RowManager.adjustTableSize (RowManager.js:1069:11)
```

**Tabulator Info**
- Which version of Tabulator are you using?

5.6.1

**Working Example**

https://jsfiddle.net/20efovmx/41/

**To Reproduce**

1. open to jsfiddle
2. open up chrome dev tools
3. wait for datatable to render

**Expected behavior**

No error in chrome dev tools

**Screenshots**

![Screenshot 2024-03-01 at 10 34 55 pm](https://github.com/olifolkerd/tabulator/assets/1418791/2c0d741a-bd69-41cc-9743-066f3d8675d7)

**Desktop (please complete the following information):**
 - OS: mac osx
 - Browser chrome
 - Version latest

**Additional context**

When downgrading tabulator to 5.6.0 there are no errors and the page doesn't crash.

**Comment by MetallianFR68** [comment]
I have the exact same problem.
I struggled to understand the reason before seeing this issue on github.
Setting both height and maxHeight seems to solve the problem

**Comment by Jojoshua** [comment]
We're experiencing the same issue after trying to upgrade from 5.5.2 to 6.2.1

**Comment by danielHin** [comment]
+1 

First time experienced this issue when updated chrome to Version 129.0.6668.58 (Official Build) (64-bit)

I have height and max-height set as mentioned here but not solving this issue in all places. 
Setting the height to fixed pixel height its fixed. only with 100% or max-content I'm facing this issue

**Comment by rkent** [comment]
I am also experiencing this. First-time user here.

There is clearly an internal loop in some cases. In my case, using as Tabulator in Firefox:
```html
<script type="text/javascript" src="https://unpkg.com/tabulator-tables@6.2.5/dist/js/tabulator.js"></script>
```
I get the following error on failure:
```
Uncaught (in promise) InternalError: too much recursion
```
Looking at the console output, the looping is clear from a snippet of the displayed call stack:
```
    adjustTableSize RowManager.js:1067
    _virtualRenderFill VirtualDomVertical.js:346
    rerenderRows VirtualDomVertical.js:101
    reRenderInPosition RowManager.js:854
    redraw RowManager.js:1116
    tableResized ResizeTable.js:138
    _dispatch InternalEventBus.js:119
    _dispatch InternalEventBus.js:118
    _debugDispatch InternalEventBus.js:134
    dispatch CoreFeature.js:78
    adjustTableSize RowManager.js:1067
    _virtualRenderFill VirtualDomVertical.js:346
    rerenderRows VirtualDomVertical.js:101
    reRenderInPosition RowManager.js:854
    redraw RowManager.js:1116
    tableResized ResizeTable.js:138
    _dispatch InternalEventBus.js:119
    _dispatch InternalEventBus.js:118
    _debugDispatch InternalEventBus.js:134
    dispatch CoreFeature.js:78
    adjustTableSize RowManager.js:1067
```
Workaround options I explored that worked:
1. revert to 5.6.0
2. modify the source to prevent the recall of adjustTableSize in _virtualRenderFill VirtualDomVertical.js:346
3. set a table option `rowHeight:30`  This is the least intrusive, and is what I will try for now.

I suspect that the data that is causing the issue causes the row size of one of the rows to change, which then triggers a redraw, that it never escapes from. It's still early though to confirm that this workaround (setting rowHeight) works in all cases.

Amazing project, by the way! Great work overall!

**Comment by muhyilmaz** [comment]
Same issue with OperaGX and Chrome. 
```
Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at f._positionPlaceholder (RowManager.js:1012:2)
    at f.adjustTableSize (RowManager.js:1076:8)
    at f.redraw (RowManager.js:1112:8)
    at ResizeTableModule.tableResized (ResizeTable.js:138:25)
    at InternalEventBus.js:119:25
    at Array.forEach (<anonymous>)
    at R._dispatch (InternalEventBus.js:118:21)
    at f.dispatch (CoreFeature.js:78:30)
    at f.adjustTableSize (RowManager.js:1067:11)
    at f._showPlaceholder (RowManager.js:998:9)
```
With Edge, it has no problem.

**Comment by olifolkerd** [comment]
Does anyone have a js fiddle that replicates this issue?

**Comment by rkent** [comment]
Try https://jsfiddle.net/rkent/5mzb9fc1/2/

Run this. At least in Firefox 130.0.1 (on Ubuntu), the "too much recursion" error occurs after a few seconds, and the table appears a few seconds later.

(This is a scaled-down version of code from https://github.com/rkent/rosindex)

**Comment by rain01** [comment]
This is still an issue in version v6.4.0.

The `rowHeight: 30` fix that @rkent suggested avoids it though.
Thank you @rkent
